app: vjepa_tr2
eval_name: vjepa_tr2
cpus_per_task: 12
task_name: pick_and_place_0530_merged
# folder: outputs/${task_name}/${now:%Y.%m.%d}_${now:%H.%M.%S}
folder: outputs/pick_and_place_0530_merged/2025.07.09_18.46.30
mem_per_gpu: 20G
nodes: 1
tasks_per_node: 8
logging:
  enable: true
  run_name: ${task_name}_${now:%Y.%m.%d}_${now:%H.%M.%S}
data:
  val_ratio : 0.05
  batch_size: 1
  camera_views:
  - cam_high_image
  crop_size: 240
  datasets:
    - /data/TR2/zcai/pick_and_place_0530_merged/raw
  dataset_fpcs:
  - 8
  fps: 4
  num_workers: 12
  patch_size: 16
  pin_mem: true
  stereo_view: false
  tubelet_size: 2
data_aug:
  auto_augment: false
  horizontal_flip: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.75
  - 1.35
  random_resize_scale:
  - 1.777
  - 1.777
  reprob: 0.0
loss:
  auto_steps: 2
  loss_exp: 1.0
  normalize_reps: true
  reg_coeff: 0.0
meta:
  dtype: bfloat16
  eval_freq: 100
  resume_checkpoint: null
  load_predictor: false
  pretrain_checkpoint: /data/shared_weights/vjepa2/vitg.pt
  context_encoder_key: target_encoder
  target_encoder_key: target_encoder
  save_every_freq: 25
  val_every_freq: 1
  compute_action_mse_every: 1
  seed: 239
  use_sdpa: true
model:
  model_name: vit_giant_xformers
  pred_depth: 24
  pred_embed_dim: 1024
  pred_is_frame_causal: true
  pred_num_heads: 16
  uniform_power: true
  use_activation_checkpointing: true
  use_extrinsics: false
  use_rope: true
optimization:
  anneal: 15
  epochs: 315
  final_lr: 0.0
  final_weight_decay: 0.04
  lr: 0.000425
  start_lr: 0.000075
  warmup: 15
  weight_decay: 0.04
